//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElmatSvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elmatEntities : DbContext
    {
        public elmatEntities()
            : base("name=elmatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FRIENDS> FRIENDS { get; set; }
        public virtual DbSet<RELATION_STATUS> RELATION_STATUS { get; set; }
        public virtual DbSet<RIDE> RIDE { get; set; }
        public virtual DbSet<ROUTINE> ROUTINE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
