//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElmatSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRIENDS
    {
        public int UserID_A { get; set; }
        public int UserID_B { get; set; }
        public long StatusID { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual RELATION_STATUS RELATION_STATUS { get; set; }
    }
}
