//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElmatSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATION_STATUS
    {
        public RELATION_STATUS()
        {
            this.FRIENDS = new HashSet<FRIENDS>();
        }
    
        public long StatusID { get; set; }
        public string StatusDescription { get; set; }
    
        public virtual ICollection<FRIENDS> FRIENDS { get; set; }
    }
}
