//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElmatSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIDE
    {
        public int RideID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Hour { get; set; }
        public long LatOrg { get; set; }
        public long LonOrg { get; set; }
        public long LatDest { get; set; }
        public long LonDest { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
